// ISO 3166-1 alpha-2 countries (plus Kosovo, XK) with English and Indonesian
// names, generated from the Unicode CLDR data built into Node's Intl. Keep the
// codes in sync with countryCodes in backend/internal/web/about.go.
import type { Locale } from "./i18n";

const COUNTRIES: [code: string, en: string, id: string][] = [
  ["AF", "Afghanistan", "Afganistan"],
  ["AX", "Åland Islands", "Kepulauan Aland"],
  ["AL", "Albania", "Albania"],
  ["DZ", "Algeria", "Aljazair"],
  ["AS", "American Samoa", "Samoa Amerika"],
  ["AD", "Andorra", "Andorra"],
  ["AO", "Angola", "Angola"],
  ["AI", "Anguilla", "Anguilla"],
  ["AQ", "Antarctica", "Antarktika"],
  ["AG", "Antigua & Barbuda", "Antigua dan Barbuda"],
  ["AR", "Argentina", "Argentina"],
  ["AM", "Armenia", "Armenia"],
  ["AW", "Aruba", "Aruba"],
  ["AU", "Australia", "Australia"],
  ["AT", "Austria", "Austria"],
  ["AZ", "Azerbaijan", "Azerbaijan"],
  ["BS", "Bahamas", "Bahama"],
  ["BH", "Bahrain", "Bahrain"],
  ["BD", "Bangladesh", "Bangladesh"],
  ["BB", "Barbados", "Barbados"],
  ["BY", "Belarus", "Belarus"],
  ["BE", "Belgium", "Belgia"],
  ["BZ", "Belize", "Belize"],
  ["BJ", "Benin", "Benin"],
  ["BM", "Bermuda", "Bermuda"],
  ["BT", "Bhutan", "Bhutan"],
  ["BO", "Bolivia", "Bolivia"],
  ["BA", "Bosnia & Herzegovina", "Bosnia dan Herzegovina"],
  ["BW", "Botswana", "Botswana"],
  ["BV", "Bouvet Island", "Pulau Bouvet"],
  ["BR", "Brazil", "Brasil"],
  ["IO", "British Indian Ocean Territory", "Wilayah Inggris di Samudra Hindia"],
  ["VG", "British Virgin Islands", "Kepulauan Virgin Britania Raya"],
  ["BN", "Brunei", "Brunei"],
  ["BG", "Bulgaria", "Bulgaria"],
  ["BF", "Burkina Faso", "Burkina Faso"],
  ["BI", "Burundi", "Burundi"],
  ["KH", "Cambodia", "Kamboja"],
  ["CM", "Cameroon", "Kamerun"],
  ["CA", "Canada", "Kanada"],
  ["CV", "Cape Verde", "Tanjung Verde"],
  ["BQ", "Caribbean Netherlands", "Belanda Karibia"],
  ["KY", "Cayman Islands", "Kepulauan Cayman"],
  ["CF", "Central African Republic", "Republik Afrika Tengah"],
  ["TD", "Chad", "Chad"],
  ["CL", "Chile", "Cile"],
  ["CN", "China", "Tiongkok"],
  ["CX", "Christmas Island", "Pulau Natal"],
  ["CC", "Cocos (Keeling) Islands", "Kepulauan Cocos (Keeling)"],
  ["CO", "Colombia", "Kolombia"],
  ["KM", "Comoros", "Komoro"],
  ["CG", "Congo - Brazzaville", "Kongo - Brazzaville"],
  ["CD", "Congo - Kinshasa", "Kongo - Kinshasa"],
  ["CK", "Cook Islands", "Kepulauan Cook"],
  ["CR", "Costa Rica", "Kosta Rika"],
  ["CI", "Côte d’Ivoire", "Côte d’Ivoire"],
  ["HR", "Croatia", "Kroasia"],
  ["CU", "Cuba", "Kuba"],
  ["CW", "Curaçao", "Curaçao"],
  ["CY", "Cyprus", "Siprus"],
  ["CZ", "Czechia", "Ceko"],
  ["DK", "Denmark", "Denmark"],
  ["DJ", "Djibouti", "Jibuti"],
  ["DM", "Dominica", "Dominika"],
  ["DO", "Dominican Republic", "Republik Dominika"],
  ["EC", "Ecuador", "Ekuador"],
  ["EG", "Egypt", "Mesir"],
  ["SV", "El Salvador", "El Salvador"],
  ["GQ", "Equatorial Guinea", "Guinea Ekuatorial"],
  ["ER", "Eritrea", "Eritrea"],
  ["EE", "Estonia", "Estonia"],
  ["SZ", "Eswatini", "eSwatini"],
  ["ET", "Ethiopia", "Etiopia"],
  ["FK", "Falkland Islands", "Kepulauan Falkland"],
  ["FO", "Faroe Islands", "Kepulauan Faroe"],
  ["FJ", "Fiji", "Fiji"],
  ["FI", "Finland", "Finlandia"],
  ["FR", "France", "Prancis"],
  ["GF", "French Guiana", "Guyana Prancis"],
  ["PF", "French Polynesia", "Polinesia Prancis"],
  ["TF", "French Southern Territories", "Wilayah Selatan Prancis"],
  ["GA", "Gabon", "Gabon"],
  ["GM", "Gambia", "Gambia"],
  ["GE", "Georgia", "Georgia"],
  ["DE", "Germany", "Jerman"],
  ["GH", "Ghana", "Ghana"],
  ["GI", "Gibraltar", "Gibraltar"],
  ["GR", "Greece", "Yunani"],
  ["GL", "Greenland", "Greenland"],
  ["GD", "Grenada", "Grenada"],
  ["GP", "Guadeloupe", "Guadeloupe"],
  ["GU", "Guam", "Guam"],
  ["GT", "Guatemala", "Guatemala"],
  ["GG", "Guernsey", "Guernsey"],
  ["GN", "Guinea", "Guinea"],
  ["GW", "Guinea-Bissau", "Guinea-Bissau"],
  ["GY", "Guyana", "Guyana"],
  ["HT", "Haiti", "Haiti"],
  ["HM", "Heard & McDonald Islands", "Pulau Heard dan Kepulauan McDonald"],
  ["HN", "Honduras", "Honduras"],
  ["HK", "Hong Kong SAR China", "Hong Kong DAK Tiongkok"],
  ["HU", "Hungary", "Hungaria"],
  ["IS", "Iceland", "Islandia"],
  ["IN", "India", "India"],
  ["ID", "Indonesia", "Indonesia"],
  ["IR", "Iran", "Iran"],
  ["IQ", "Iraq", "Irak"],
  ["IE", "Ireland", "Irlandia"],
  ["IM", "Isle of Man", "Pulau Man"],
  ["IL", "Israel", "Israel"],
  ["IT", "Italy", "Italia"],
  ["JM", "Jamaica", "Jamaika"],
  ["JP", "Japan", "Jepang"],
  ["JE", "Jersey", "Jersey"],
  ["JO", "Jordan", "Yordania"],
  ["KZ", "Kazakhstan", "Kazakhstan"],
  ["KE", "Kenya", "Kenya"],
  ["KI", "Kiribati", "Kiribati"],
  ["XK", "Kosovo", "Kosovo"],
  ["KW", "Kuwait", "Kuwait"],
  ["KG", "Kyrgyzstan", "Kirgizstan"],
  ["LA", "Laos", "Laos"],
  ["LV", "Latvia", "Latvia"],
  ["LB", "Lebanon", "Lebanon"],
  ["LS", "Lesotho", "Lesotho"],
  ["LR", "Liberia", "Liberia"],
  ["LY", "Libya", "Libya"],
  ["LI", "Liechtenstein", "Liechtenstein"],
  ["LT", "Lithuania", "Lituania"],
  ["LU", "Luxembourg", "Luksemburg"],
  ["MO", "Macao SAR China", "Makau DAK Tiongkok"],
  ["MG", "Madagascar", "Madagaskar"],
  ["MW", "Malawi", "Malawi"],
  ["MY", "Malaysia", "Malaysia"],
  ["MV", "Maldives", "Maladewa"],
  ["ML", "Mali", "Mali"],
  ["MT", "Malta", "Malta"],
  ["MH", "Marshall Islands", "Kepulauan Marshall"],
  ["MQ", "Martinique", "Martinik"],
  ["MR", "Mauritania", "Mauritania"],
  ["MU", "Mauritius", "Mauritius"],
  ["YT", "Mayotte", "Mayotte"],
  ["MX", "Mexico", "Meksiko"],
  ["FM", "Micronesia", "Mikronesia"],
  ["MD", "Moldova", "Moldova"],
  ["MC", "Monaco", "Monako"],
  ["MN", "Mongolia", "Mongolia"],
  ["ME", "Montenegro", "Montenegro"],
  ["MS", "Montserrat", "Montserrat"],
  ["MA", "Morocco", "Maroko"],
  ["MZ", "Mozambique", "Mozambik"],
  ["MM", "Myanmar (Burma)", "Myanmar (Burma)"],
  ["NA", "Namibia", "Namibia"],
  ["NR", "Nauru", "Nauru"],
  ["NP", "Nepal", "Nepal"],
  ["NL", "Netherlands", "Belanda"],
  ["NC", "New Caledonia", "Kaledonia Baru"],
  ["NZ", "New Zealand", "Selandia Baru"],
  ["NI", "Nicaragua", "Nikaragua"],
  ["NE", "Niger", "Niger"],
  ["NG", "Nigeria", "Nigeria"],
  ["NU", "Niue", "Niue"],
  ["NF", "Norfolk Island", "Kepulauan Norfolk"],
  ["KP", "North Korea", "Korea Utara"],
  ["MK", "North Macedonia", "Makedonia Utara"],
  ["MP", "Northern Mariana Islands", "Kepulauan Mariana Utara"],
  ["NO", "Norway", "Norwegia"],
  ["OM", "Oman", "Oman"],
  ["PK", "Pakistan", "Pakistan"],
  ["PW", "Palau", "Palau"],
  ["PS", "Palestinian Territories", "Wilayah Palestina"],
  ["PA", "Panama", "Panama"],
  ["PG", "Papua New Guinea", "Papua Nugini"],
  ["PY", "Paraguay", "Paraguay"],
  ["PE", "Peru", "Peru"],
  ["PH", "Philippines", "Filipina"],
  ["PN", "Pitcairn Islands", "Kepulauan Pitcairn"],
  ["PL", "Poland", "Polandia"],
  ["PT", "Portugal", "Portugal"],
  ["PR", "Puerto Rico", "Puerto Riko"],
  ["QA", "Qatar", "Qatar"],
  ["RE", "Réunion", "Réunion"],
  ["RO", "Romania", "Rumania"],
  ["RU", "Russia", "Rusia"],
  ["RW", "Rwanda", "Rwanda"],
  ["WS", "Samoa", "Samoa"],
  ["SM", "San Marino", "San Marino"],
  ["ST", "São Tomé & Príncipe", "Sao Tome dan Principe"],
  ["SA", "Saudi Arabia", "Arab Saudi"],
  ["SN", "Senegal", "Senegal"],
  ["RS", "Serbia", "Serbia"],
  ["SC", "Seychelles", "Seychelles"],
  ["SL", "Sierra Leone", "Sierra Leone"],
  ["SG", "Singapore", "Singapura"],
  ["SX", "Sint Maarten", "Sint Maarten"],
  ["SK", "Slovakia", "Slovakia"],
  ["SI", "Slovenia", "Slovenia"],
  ["SB", "Solomon Islands", "Kepulauan Solomon"],
  ["SO", "Somalia", "Somalia"],
  ["ZA", "South Africa", "Afrika Selatan"],
  ["GS", "South Georgia & South Sandwich Islands", "Georgia Selatan & Kep. Sandwich Selatan"],
  ["KR", "South Korea", "Korea Selatan"],
  ["SS", "South Sudan", "Sudan Selatan"],
  ["ES", "Spain", "Spanyol"],
  ["LK", "Sri Lanka", "Sri Lanka"],
  ["BL", "St. Barthélemy", "Saint Barthélemy"],
  ["SH", "St. Helena", "Saint Helena"],
  ["KN", "St. Kitts & Nevis", "Saint Kitts dan Nevis"],
  ["LC", "St. Lucia", "Saint Lucia"],
  ["MF", "St. Martin", "Saint Martin"],
  ["PM", "St. Pierre & Miquelon", "Saint Pierre dan Miquelon"],
  ["VC", "St. Vincent & Grenadines", "Saint Vincent dan Grenadine"],
  ["SD", "Sudan", "Sudan"],
  ["SR", "Suriname", "Suriname"],
  ["SJ", "Svalbard & Jan Mayen", "Kepulauan Svalbard dan Jan Mayen"],
  ["SE", "Sweden", "Swedia"],
  ["CH", "Switzerland", "Swiss"],
  ["SY", "Syria", "Suriah"],
  ["TW", "Taiwan", "Taiwan"],
  ["TJ", "Tajikistan", "Tajikistan"],
  ["TZ", "Tanzania", "Tanzania"],
  ["TH", "Thailand", "Thailand"],
  ["TL", "Timor-Leste", "Timor Leste"],
  ["TG", "Togo", "Togo"],
  ["TK", "Tokelau", "Tokelau"],
  ["TO", "Tonga", "Tonga"],
  ["TT", "Trinidad & Tobago", "Trinidad dan Tobago"],
  ["TN", "Tunisia", "Tunisia"],
  ["TR", "Türkiye", "Turki"],
  ["TM", "Turkmenistan", "Turkmenistan"],
  ["TC", "Turks & Caicos Islands", "Kepulauan Turks dan Caicos"],
  ["TV", "Tuvalu", "Tuvalu"],
  ["UM", "U.S. Outlying Islands", "Kepulauan Terluar AS"],
  ["VI", "U.S. Virgin Islands", "Kepulauan Virgin Amerika Serikat"],
  ["UG", "Uganda", "Uganda"],
  ["UA", "Ukraine", "Ukraina"],
  ["AE", "United Arab Emirates", "Uni Emirat Arab"],
  ["GB", "United Kingdom", "Inggris Raya"],
  ["US", "United States", "Amerika Serikat"],
  ["UY", "Uruguay", "Uruguay"],
  ["UZ", "Uzbekistan", "Uzbekistan"],
  ["VU", "Vanuatu", "Vanuatu"],
  ["VA", "Vatican City", "Vatikan"],
  ["VE", "Venezuela", "Venezuela"],
  ["VN", "Vietnam", "Vietnam"],
  ["WF", "Wallis & Futuna", "Kepulauan Wallis dan Futuna"],
  ["EH", "Western Sahara", "Sahara Barat"],
  ["YE", "Yemen", "Yaman"],
  ["ZM", "Zambia", "Zambia"],
  ["ZW", "Zimbabwe", "Zimbabwe"],
];

export function countryName(code: string, lang: Locale): string {
  const row = COUNTRIES.find(([c]) => c === code);
  return row ? (lang === "id" ? row[2] : row[1]) : code;
}

// Countries sorted by name in lang, for pickers.
export function countriesFor(lang: Locale): { code: string; name: string }[] {
  return COUNTRIES.map(([code]) => ({ code, name: countryName(code, lang) })).sort((a, b) => a.name.localeCompare(b.name));
}

// The flag emoji for a country code: two regional-indicator letters, which
// systems with flag fonts draw as the flag (others show the letters).
export function flagEmoji(code: string): string {
  if (!/^[A-Z]{2}$/.test(code)) return "";
  return String.fromCodePoint(...[...code].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65));
}
